// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDangkouConfig() {
  return window['go']['main']['App']['GetDangkouConfig']();
}

export function GetFilterConfig() {
  return window['go']['main']['App']['GetFilterConfig']();
}

export function GetPeijianConfig() {
  return window['go']['main']['App']['GetPeijianConfig']();
}

export function HandleDroppedFile(arg1, arg2) {
  return window['go']['main']['App']['HandleDroppedFile'](arg1, arg2);
}

export function OpenDir(arg1) {
  return window['go']['main']['App']['OpenDir'](arg1);
}

export function RunDangkou(arg1) {
  return window['go']['main']['App']['RunDangkou'](arg1);
}

export function RunFilter(arg1) {
  return window['go']['main']['App']['RunFilter'](arg1);
}

export function RunPeijianExtract(arg1) {
  return window['go']['main']['App']['RunPeijianExtract'](arg1);
}

export function RunPeijianMerge(arg1) {
  return window['go']['main']['App']['RunPeijianMerge'](arg1);
}

export function SaveDangkouConfig(arg1) {
  return window['go']['main']['App']['SaveDangkouConfig'](arg1);
}

export function SaveFilterConfig(arg1) {
  return window['go']['main']['App']['SaveFilterConfig'](arg1);
}

export function SavePeijianConfig(arg1) {
  return window['go']['main']['App']['SavePeijianConfig'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
