// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDangkouConfigPath():Promise<string>;

export function GetFilterConfig():Promise<main.FilterConfig>;

export function GetPeijianConfigPath():Promise<string>;

export function GetPizhiConfigPath():Promise<string>;

export function HandleDroppedFile(arg1:string,arg2:string):Promise<string>;

export function OpenDir(arg1:string):Promise<void>;

export function RunDangkou(arg1:string):Promise<main.DangkouResult>;

export function RunFilter(arg1:string):Promise<main.FilterResult>;

export function RunPeijianProcess(arg1:string):Promise<main.PeijianResult>;

export function RunPizhiProcess(arg1:string):Promise<main.PizhiResult>;

export function SaveDangkouConfigPath(arg1:string):Promise<void>;

export function SaveFilterConfig(arg1:main.FilterConfig):Promise<void>;

export function SavePeijianConfigPath(arg1:string):Promise<void>;

export function SavePizhiConfigPath(arg1:string):Promise<void>;

export function SelectDangkouConfigFile():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectPeijianConfigFile():Promise<string>;

export function SelectPizhiConfigFile():Promise<string>;
