// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDangkouConfigPath() {
  return window['go']['main']['App']['GetDangkouConfigPath']();
}

export function GetFilterConfig() {
  return window['go']['main']['App']['GetFilterConfig']();
}

export function GetPeijianConfigPath() {
  return window['go']['main']['App']['GetPeijianConfigPath']();
}

export function HandleDroppedFile(arg1, arg2) {
  return window['go']['main']['App']['HandleDroppedFile'](arg1, arg2);
}

export function OpenDir(arg1) {
  return window['go']['main']['App']['OpenDir'](arg1);
}

export function RunDangkou(arg1) {
  return window['go']['main']['App']['RunDangkou'](arg1);
}

export function RunFilter(arg1) {
  return window['go']['main']['App']['RunFilter'](arg1);
}

export function RunPeijianProcess(arg1) {
  return window['go']['main']['App']['RunPeijianProcess'](arg1);
}

export function SaveDangkouConfigPath(arg1) {
  return window['go']['main']['App']['SaveDangkouConfigPath'](arg1);
}

export function SaveFilterConfig(arg1) {
  return window['go']['main']['App']['SaveFilterConfig'](arg1);
}

export function SavePeijianConfigPath(arg1) {
  return window['go']['main']['App']['SavePeijianConfigPath'](arg1);
}

export function SelectDangkouConfigFile() {
  return window['go']['main']['App']['SelectDangkouConfigFile']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectPeijianConfigFile() {
  return window['go']['main']['App']['SelectPeijianConfigFile']();
}
